'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WeeklyScoringUpdate

    '''<summary>
    '''TeamsByGameTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing1B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1B As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TeamsByGameTable2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable2 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing5A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing5B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing5B As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TeamsByGameTable3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable3 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing9A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing9A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing9B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing9B As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TeamsByGameTable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable4 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing13A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing13A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing13B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing13B As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
